name: ssec-learnathon
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Python dependencies
  - python=3.10
  - pip
  # Jupyterbook dependencies
  - jupyter-book
  - jupyterlab
  # UI dependencies
  - dask-labextension
  - jupyterlab-myst
  - jupyter-resource-usage
  - jupytext
  # Scientific dependencies
  - xarray
  - dask
  - distributed
  - pydantic>=2
  - matplotlib
  # Data io dependencies
  - fsspec
  - s3fs
  - zarr
  - pooch
  - netcdf4
  # Cloud dependencies
  - terraform
  - awscli
  # Pip install packages
  - pip:
    - graphviz
platforms:
  - linux-64
  - osx-64
  - osx-arm64
