name: CI

on:
  push:
    branches: main
    paths: book/**
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# Environment variables
env:
    CONDA_ENV: 'ssec-learnathon'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JupyterBook Cache
        uses: actions/cache@v3
        with:
          path: _build
          # NOTE: change key to "jupyterbook-DATE" to force rebuilding cache
          key: jupyterbook-20230817

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
            environment-file: conda/conda-lock.yml
            environment-name: ${{ env.CONDA_ENV }}
            cache-environment: true

      - name: Build JupyterBook
        # NOTE: login shell activates conda environment
        shell: bash -el {0}
        run: |
          jupyter-book build ./book --keep-going

      - name: Dump Build Logs
        if: always()
        run: |
          if (test -a book/_build/html/reports/*log); then cat book/_build/html/reports/*log ; fi

      - name: Save Build
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: book/_build/

      - name: Publish to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html
          publish_branch: gh-pages
          enable_jekyll: false
